In [1]:
import numpy as np
import pandas as pd

In [2]:
import datetime as dt

In [3]:
import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import session, sessionmaker, relationship
from sqlalchemy import create_engine, func

In [4]:
import sqlite3

## Database Creation

In [5]:
conn = sqlite3.connect("covid_2.db")

In [6]:
c = conn.cursor()

In [7]:
machine_learning_data = pd.read_csv("Datasets_HL/ML_Models/2.0_ML_Data.csv")
machine_learning_data.to_sql('machine_learning_data', conn, if_exists='append', index = False,)

C:\Users\hzlip\anaconda3\envs\mlenv\lib\site-packages\pandas\core\generic.py:2789: UserWarning: The spaces in these column names will not be changed. In pandas versions < 0.14, spaces were converted to underscores.
  method=method,

In [8]:
# model_machine_learning_data = pd.read_csv('Datasets_HL/ML_Models/Model_Machine_Learning_Data.csv')
# model_machine_learning_data.to_sql('covid_2.db', conn, if_exists='append', index = False,)

In [9]:
health_data = pd.read_csv('Datasets_HL/Obesity_and_Health/County_Health_Clean.csv')
health_data.to_sql('health_data', conn, if_exists='append', index = False,)

## Database Viewing

In [10]:
# SQLAlchemy
from sqlalchemy import create_engine
from sqlalchemy import inspect
# Pandas
import pandas as pd

# Path to sqlite
database_path = "covid_2.db"

In [11]:
# Create an engine that can talk to the database
engine = create_engine(f"sqlite:///{database_path}")

In [12]:
# Get the name of the table. 
inspector = inspect(engine)
inspector.get_table_names()

['health_data', 'machine_learning_data', 'model_machine_learning_data']

In [13]:
# Using the inspector to print the column names within the 'Census_Data' table and its types
columns = inspector.get_columns('health_data')
pd.DataFrame(columns)

,name,type,nullable,default,autoincrement,primary_key
0,FIPS,INTEGER,True,None,auto,0
1,Adult Obesity Percent,REAL,True,None,auto,0
2,Adult Smoking Percentage,REAL,True,None,auto,0
3,Excessive Drinking Percent,REAL,True,None,auto,0

In [14]:
# Using the inspector to print the column names within the 'Census_Data' table and its types
columns = inspector.get_columns('machine_learning_data')
pd.DataFrame(columns)

,name,type,nullable,default,autoincrement,primary_key
0,FIPS,INTEGER,True,None,auto,0
1,State,TEXT,True,None,auto,0
2,County Name,TEXT,True,None,auto,0
3,Urban Rural Code,REAL,True,None,auto,0
4,Urban Rural Description,TEXT,True,None,auto,0
5,Population Estimate 2020,REAL,True,None,auto,0
6,Median Age of County,REAL,True,None,auto,0
7,Total Vaccines,REAL,True,None,auto,0
8,Percent Vaccinated,REAL,True,None,auto,0
9,Case Count,REAL,True,None,auto,0
10,Percent of Population Cases,REAL,True,None,auto,0
11,COVID-19 Deaths,REAL,True,None,auto,0
12,Percent Population Died from Covid,REAL,True,None,auto,0
13,Percent Population Died by Covid above Median ...,REAL,True,None,auto,0

In [15]:
# Using the inspector to print the column names within the 'Census_Data' table and its types
columns = inspector.get_columns('model_machine_learning_data')
pd.DataFrame(columns)

,name,type,nullable,default,autoincrement,primary_key
0,FIPS,INTEGER,True,None,auto,0
1,State,TEXT,True,None,auto,0
2,County Name,TEXT,True,None,auto,0
3,Urban Rural Code,REAL,True,None,auto,0
4,Urban Rural Description,TEXT,True,None,auto,0
5,Population Estimate 2020,REAL,True,None,auto,0
6,Median Age of County,REAL,True,None,auto,0
7,Total Vaccines,REAL,True,None,auto,0
8,Percent Vaccinated,REAL,True,None,auto,0
9,Case Count,REAL,True,None,auto,0
10,Percent of Population Cases,REAL,True,None,auto,0
11,COVID-19 Deaths,REAL,True,None,auto,0
12,Percent Population Died from Covid,REAL,True,None,auto,0
13,Percent Population Died by Covid above Median ...,REAL,True,None,auto,0
14,FIPS:1,INTEGER,True,None,auto,0
15,Adult Obesity Percent,REAL,True,None,auto,0
16,Adult Smoking Percentage,REAL,True,None,auto,0
17,Excessive Drinking Percent,REAL,True,None,auto,0