In [1]:
import pandas as pd

In [2]:
health_data = pd.read_csv("../Obesity_and_Health/analytic_data2021.csv")
health_data

C:\Users\hzlip\anaconda3\envs\mlenv\lib\site-packages\IPython\core\interactiveshell.py:3166: DtypeWarning: Columns (0,1,2,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,State FIPS Code,County FIPS Code,5-digit FIPS Code,State Abbreviation,Name,Release Year,County Ranked (Yes=1/No=0),Premature death raw value,Premature death numerator,Premature death denominator,...,% Females raw value,% Females numerator,% Females denominator,% Females CI low,% Females CI high,% Rural raw value,% Rural numerator,% Rural denominator,% Rural CI low,% Rural CI high
0,statecode,countycode,fipscode,state,county,year,county_ranked,v001_rawvalue,v001_numerator,v001_denominator,...,v057_rawvalue,v057_numerator,v057_denominator,v057_cilow,v057_cihigh,v058_rawvalue,v058_numerator,v058_denominator,v058_cilow,v058_cihigh
1,00,000,00000,US,United States,2021,NaN,6906.6410942,3854074,915437195,...,0.5075019531,166582199,328239523,NaN,NaN,0.1926902892,NaN,NaN,NaN,NaN
2,01,000,01000,AL,Alabama,2021,NaN,9819.8874313,82249,13651801,...,0.5167392215,2533668,4903185,NaN,NaN,0.409631829,1957932,4779736,NaN,NaN
3,01,001,01001,AL,Autauga County,2021,1,7830.0534837,787,155765,...,0.5150799191,28777,55869,NaN,NaN,0.4200216232,22921,54571,NaN,NaN
4,01,003,01003,AL,Baldwin County,2021,1,7680.4772697,3147,600539,...,0.5150962667,114987,223234,NaN,NaN,0.4227909911,77060,182265,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3190,56,37,56037,WY,Sweetwater County,2021,1.0,7775.070675,527,123565,...,0.484968,20535,42343,NaN,NaN,0.109163,4782,43806,NaN,NaN
3191,56,39,56039,WY,Teton County,2021,1.0,2979.684888,109,66075,...,0.482526,11322,23464,NaN,NaN,0.464309,9887,21294,NaN,NaN
3192,56,41,56041,WY,Uinta County,2021,1.0,8081.051208,271,58124,...,0.494512,10002,20226,NaN,NaN,0.430959,9101,21118,NaN,NaN
3193,56,43,56043,WY,Washakie County,2021,1.0,6541.07415,104,21447,...,0.492249,3842,7805,NaN,NaN,0.359545,3068,8533,NaN,NaN
3194,56,45,56045,WY,Weston County,2021,1.0,3858.465676,76,18989,...,0.47683,3303,6927,NaN,NaN,0.545366,3931,7208,NaN,NaN

In [3]:
health_data

,State FIPS Code,County FIPS Code,5-digit FIPS Code,State Abbreviation,Name,Release Year,County Ranked (Yes=1/No=0),Premature death raw value,Premature death numerator,Premature death denominator,...,% Females raw value,% Females numerator,% Females denominator,% Females CI low,% Females CI high,% Rural raw value,% Rural numerator,% Rural denominator,% Rural CI low,% Rural CI high
0,statecode,countycode,fipscode,state,county,year,county_ranked,v001_rawvalue,v001_numerator,v001_denominator,...,v057_rawvalue,v057_numerator,v057_denominator,v057_cilow,v057_cihigh,v058_rawvalue,v058_numerator,v058_denominator,v058_cilow,v058_cihigh
1,00,000,00000,US,United States,2021,NaN,6906.6410942,3854074,915437195,...,0.5075019531,166582199,328239523,NaN,NaN,0.1926902892,NaN,NaN,NaN,NaN
2,01,000,01000,AL,Alabama,2021,NaN,9819.8874313,82249,13651801,...,0.5167392215,2533668,4903185,NaN,NaN,0.409631829,1957932,4779736,NaN,NaN
3,01,001,01001,AL,Autauga County,2021,1,7830.0534837,787,155765,...,0.5150799191,28777,55869,NaN,NaN,0.4200216232,22921,54571,NaN,NaN
4,01,003,01003,AL,Baldwin County,2021,1,7680.4772697,3147,600539,...,0.5150962667,114987,223234,NaN,NaN,0.4227909911,77060,182265,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3190,56,37,56037,WY,Sweetwater County,2021,1.0,7775.070675,527,123565,...,0.484968,20535,42343,NaN,NaN,0.109163,4782,43806,NaN,NaN
3191,56,39,56039,WY,Teton County,2021,1.0,2979.684888,109,66075,...,0.482526,11322,23464,NaN,NaN,0.464309,9887,21294,NaN,NaN
3192,56,41,56041,WY,Uinta County,2021,1.0,8081.051208,271,58124,...,0.494512,10002,20226,NaN,NaN,0.430959,9101,21118,NaN,NaN
3193,56,43,56043,WY,Washakie County,2021,1.0,6541.07415,104,21447,...,0.492249,3842,7805,NaN,NaN,0.359545,3068,8533,NaN,NaN
3194,56,45,56045,WY,Weston County,2021,1.0,3858.465676,76,18989,...,0.47683,3303,6927,NaN,NaN,0.545366,3931,7208,NaN,NaN

In [4]:
#Info From University of Wisconson
health_df = health_data.filter(["5-digit FIPS Code", "Adult obesity raw value", "Adult smoking raw value", "Poor of fair health raw value", "Excessive drinking raw value"])
health_df

,5-digit FIPS Code,Adult obesity raw value,Adult smoking raw value,Excessive drinking raw value
0,fipscode,v011_rawvalue,v009_rawvalue,v049_rawvalue
1,00000,0.297,0.1662246666,0.191745811
2,01000,0.361,0.1998983096,0.1489137764
3,01001,0.33,0.1981076587,0.1447388631
4,01003,0.3,0.1851331826,0.1873695763
...,...,...,...,...
3190,56037,0.303,0.185086,0.19188
3191,56039,0.11,0.128844,0.237739
3192,56041,0.352,0.207645,0.184073
3193,56043,0.292,0.194425,0.193291
3194,56045,0.372,0.206386,0.197149

In [5]:
health_df = health_df.rename({"5-digit FIPS Code": "FIPS", "Adult obesity raw value":"Adult Obesity Percent", "Adult smoking raw value": "Adult Smoking Percentage", "Excessive drinking raw value": "Excessive Drinking Percent"}, axis=1)

In [9]:
health_df = health_df[1:]
health_df

,FIPS,Adult Obesity Percent,Adult Smoking Percentage,Excessive Drinking Percent
1,00000,0.297,0.1662246666,0.191745811
2,01000,0.361,0.1998983096,0.1489137764
3,01001,0.33,0.1981076587,0.1447388631
4,01003,0.3,0.1851331826,0.1873695763
5,01005,0.412,0.2553076754,0.1246697372
...,...,...,...,...
3190,56037,0.303,0.185086,0.19188
3191,56039,0.11,0.128844,0.237739
3192,56041,0.352,0.207645,0.184073
3193,56043,0.292,0.194425,0.193291
3194,56045,0.372,0.206386,0.197149

In [10]:
health_df.dtypes

FIPS                          object
Adult Obesity Percent         object
Adult Smoking Percentage      object
Excessive Drinking Percent    object
dtype: object

In [11]:
health_df["FIPS"]= health_df["FIPS"].astype(str).astype(int)
health_df["Adult Obesity Percent"]= health_df["Adult Obesity Percent"].astype(str).astype(float)
health_df["Adult Smoking Percentage"]= health_df["Adult Smoking Percentage"].astype(str).astype(float)
health_df["Excessive Drinking Percent"]= health_df["Excessive Drinking Percent"].astype(str).astype(float)

In [12]:
health_df.to_csv('County_Health_Clean.csv', index=False)